"""Remove Clipdeck's per-user desktop integration without deleting clips."""

from __future__ import annotations

import json
import os
import shlex
import shutil
import subprocess
import sys
from pathlib import Path

from install import desktop_argument


ROOT = Path(__file__).resolve().parent
USER_HOME = Path.home()
DATA_HOME = Path(os.environ.get("XDG_DATA_HOME", USER_HOME / ".local/share"))
CONFIG_HOME = Path(os.environ.get("XDG_CONFIG_HOME", USER_HOME / ".config"))


def _remove_owned_desktop(path: Path, expected_exec: str) -> bool:
    if path.is_symlink() or not path.is_file():
        return False
    lines = path.read_text(encoding="utf-8").splitlines()
    if f"Exec={expected_exec}" not in lines:
        return False
    path.unlink()
    print(f"Removed {path}")
    return True


def _remove_pair(path: Path, marker: str, line: str) -> bool:
    if path.is_symlink() or not path.is_file():
        return False
    before = path.read_text(encoding="utf-8")
    pair = marker + "\n" + line + "\n"
    if before.count(pair) != 1:
        return False
    path.write_text(before.replace(pair, "", 1), encoding="utf-8")
    print(f"Removed Clipdeck entry from {path}")
    return True


def _remove_generated_binds(path: Path, header: str) -> bool:
    if path.is_symlink() or not path.is_file():
        return False
    if path.read_text(encoding="utf-8").splitlines()[:1] != [header]:
        return False
    path.unlink()
    print(f"Removed {path}")
    return True


def remove_hyprland_entries() -> bool:
    changed = False
    run = ROOT / "run.sh"
    execs = CONFIG_HOME / "hypr/hyprland/execs.lua"
    command = json.dumps(shlex.quote(str(run)) + " --ensure-capture")
    changed |= _remove_pair(
        execs, "    -- Clipdeck background capture", f"    hl.exec_cmd({command})"
    )
    for main, binds, style in (
        (CONFIG_HOME / "caelestia/hypr-user.lua", CONFIG_HOME / "caelestia/clipdeck-binds.lua", "lua"),
        (CONFIG_HOME / "hypr/hyprland.lua", CONFIG_HOME / "hypr/clipdeck-binds.lua", "lua"),
        (CONFIG_HOME / "hypr/hyprland.conf", CONFIG_HOME / "hypr/clipdeck-binds.conf", "conf"),
    ):
        marker = "-- Clipdeck shortcuts" if style == "lua" else "# Clipdeck shortcuts"
        include = f"dofile({json.dumps(str(binds))})" if style == "lua" else f"source = {binds}"
        removed_include = _remove_pair(main, marker, include)
        changed |= removed_include
        # A generated file without an include is also safe to remove.
        header = ("-- Generated by Clipdeck. Change shortcuts in the app." if style == "lua"
                  else "# Generated by Clipdeck. Change shortcuts in the app.")
        if removed_include or not main.exists():
            changed |= _remove_generated_binds(binds, header)
    return changed


def remove_desktop_hotkeys() -> None:
    from clipdeck.hotkeys import HotkeyError, _save_desktop_hotkeys

    # Only entries with Clipdeck's own action names and commands are removed.
    for desktop in ("gnome", "cinnamon"):
        try:
            _save_desktop_hotkeys({}, desktop, owner_root=ROOT)
        except HotkeyError:
            # The other desktop's GSettings schema is often unavailable.
            pass


def main() -> int:
    if os.geteuid() == 0:
        print("Run bash ./uninstall.sh as your normal user, not with sudo.", file=sys.stderr)
        return 1

    run = desktop_argument(ROOT / "run.sh")
    _remove_owned_desktop(DATA_HOME / "applications/io.github.clipdeck.Clipdeck.desktop", run)
    _remove_owned_desktop(
        CONFIG_HOME / "autostart/io.github.clipdeck.Capture.desktop", run + " --ensure-capture"
    )

    changed_hyprland = remove_hyprland_entries()
    remove_desktop_hotkeys()
    hotkeys = CONFIG_HOME / "clipdeck/hotkeys.json"
    if hotkeys.is_file() and not hotkeys.is_symlink():
        hotkeys.unlink()
        print(f"Removed {hotkeys}")

    font = DATA_HOME / "fonts/Clipdeck-Inter.ttf"
    source_font = ROOT / "assets/fonts/Inter.ttf"
    if (font.is_file() and not font.is_symlink() and source_font.is_file()
            and font.read_bytes() == source_font.read_bytes()):
        font.unlink()
        print(f"Removed {font}")
        if shutil.which("fc-cache"):
            subprocess.run(["fc-cache", "-f", str(font.parent)], check=False)

    if changed_hyprland and os.environ.get("HYPRLAND_INSTANCE_SIGNATURE") and shutil.which("hyprctl"):
        subprocess.run(["hyprctl", "reload"], check=False)

    print("Clipdeck desktop integration removed. Clips and settings were kept.")
    print("You can now delete this checkout folder if you no longer need it:", ROOT)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except OSError as exc:
        print(f"Uninstall failed: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc
