"""Uninstall removes only integration created by this checkout."""

import json
import shlex
import tempfile
from pathlib import Path
from unittest import TestCase
from unittest.mock import patch

import uninstall


class UninstallTests(TestCase):
    def test_removes_owned_entries_but_keeps_clips_and_settings(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "checkout"
            config = Path(directory) / "config"
            data = Path(directory) / "data"
            (root / "assets/fonts").mkdir(parents=True)
            (root / "assets/fonts/Inter.ttf").write_bytes(b"font")
            font = data / "fonts/Clipdeck-Inter.ttf"
            font.parent.mkdir(parents=True)
            font.write_bytes(b"font")
            launcher = data / "applications/io.github.clipdeck.Clipdeck.desktop"
            launcher.parent.mkdir(parents=True)
            launcher.write_text(f"[Desktop Entry]\nExec={root / 'run.sh'}\n", encoding="utf-8")
            autostart = config / "autostart/io.github.clipdeck.Capture.desktop"
            autostart.parent.mkdir(parents=True)
            autostart.write_text(f"Exec={root / 'run.sh'} --ensure-capture\n", encoding="utf-8")
            settings = config / "clipdeck/settings.json"
            settings.parent.mkdir(parents=True)
            settings.write_text("{}", encoding="utf-8")
            hotkeys = settings.with_name("hotkeys.json")
            hotkeys.write_text("{}", encoding="utf-8")
            clip = Path(directory) / "Videos/clip.mkv"
            clip.parent.mkdir()
            clip.write_bytes(b"clip")
            execs = config / "hypr/hyprland/execs.lua"
            execs.parent.mkdir(parents=True)
            command = json.dumps(shlex.quote(str(root / "run.sh")) + " --ensure-capture")
            execs.write_text(
                'before\n    -- Clipdeck background capture\n'
                f'    hl.exec_cmd({command})\nafter\n', encoding="utf-8"
            )
            main = config / "hypr/hyprland.conf"
            binds = config / "hypr/clipdeck-binds.conf"
            main.write_text(f"other = keep\n# Clipdeck shortcuts\nsource = {binds}\n", encoding="utf-8")
            binds.write_text("# Generated by Clipdeck. Change shortcuts in the app.\nbind = F6\n", encoding="utf-8")
            with (patch.object(uninstall, "ROOT", root),
                  patch.object(uninstall, "CONFIG_HOME", config),
                  patch.object(uninstall, "DATA_HOME", data),
                  patch.object(uninstall.os, "geteuid", return_value=1000),
                  patch.object(uninstall, "remove_desktop_hotkeys"),
                  patch.object(uninstall.shutil, "which", return_value=None)):
                self.assertEqual(uninstall.main(), 0)
                self.assertEqual(uninstall.main(), 0)
            for path in (launcher, autostart, font, hotkeys, binds):
                self.assertFalse(path.exists(), path)
            self.assertEqual(execs.read_text(encoding="utf-8"), "before\nafter\n")
            self.assertEqual(main.read_text(encoding="utf-8"), "other = keep\n")
            self.assertTrue(settings.exists())
            self.assertEqual(clip.read_bytes(), b"clip")

    def test_does_not_remove_entry_from_another_checkout(self):
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "clipdeck.desktop"
            path.write_text("Exec=/another/clipdeck/run.sh\n", encoding="utf-8")
            self.assertFalse(uninstall._remove_owned_desktop(path, "/mine/clipdeck/run.sh"))
            self.assertTrue(path.exists())
